parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: tprinter
    database_user: tprinter
    database_password: tun3453zghbyangIk
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ada4cf9f6cdb9ad4c6bae3a4e765631a46935064
    database_path: null
